"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robotic_hand.glb --typescript 
Author: SeanNicolas (https://sketchfab.com/SeanNicolas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robotic-hand-3e284b06bbb84d858f85f7a246cd65df
Title: Robotic Hand
*/

import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import * as THREE from "three";

// Definir o tipo para o modelo GLTF
type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh;
  };
  materials: {
    [key: string]: THREE.Material;
  };
};

// Definir as props do componente
type ModelProps = JSX.IntrinsicElements["group"] & {
  // Adicione propriedades específicas se necessário
};

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF(
    "/assets/models/robotic_hand.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <group
          position={[3.709, 0.557, -1.315]}
          rotation={[Math.PI / 2, -0.509, Math.PI / 2]}
          scale={0.332}
        >
          <mesh
            geometry={nodes.Sphere008_0?.geometry}
            material={materials["Material.000"]}
          />
          <mesh
            geometry={nodes.Sphere008_1?.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.Sphere008_2?.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group position={[3.837, 0.467, -2.673]} scale={[0.061, 0.061, 0.525]}>
          <mesh
            geometry={nodes.Cylinder018_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder018_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder018_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.972, -0.889, -0.146]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.163, 0.163, 0.105]}
        >
          <mesh
            geometry={nodes.Cylinder017_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder017_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder017_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.903, -0.889, 0.962]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.117, 0.117, 0.084]}
        >
          <mesh
            geometry={nodes.Cylinder016_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder016_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder016_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.965, -0.889, 0.396]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.136, 0.136, 0.098]}
        >
          <mesh
            geometry={nodes.Cylinder015_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder015_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder015_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.062, -0.425, 0.722]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.165, 0.165, 0.119]}
        >
          <mesh
            geometry={nodes.Cylinder014_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder014_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder014_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.986, -0.425, 1.406]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.141, 0.141, 0.102]}
        >
          <mesh
            geometry={nodes.Cylinder013_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder013_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder013_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.07, -0.425, 0.065]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.198, 0.198, 0.127]}
        >
          <mesh
            geometry={nodes.Cylinder012_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder012_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder012_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.144, 0.096, 0.912]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.165, 0.165, 0.126]}
        >
          <mesh
            geometry={nodes.Cylinder011_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder011_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder011_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.069, 0.096, 1.642]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.141, 0.141, 0.107]}
        >
          <mesh
            geometry={nodes.Cylinder010_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder010_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder010_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.159, 0.096, 0.197]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.198, 0.198, 0.113]}
        >
          <mesh
            geometry={nodes.Cylinder009_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder009_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder009_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.107, 0.654, 0.198]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.198, 0.198, 0.113]}
        >
          <mesh
            geometry={nodes.Cylinder008_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder008_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder008_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.023, 0.654, 1.539]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.141, 0.141, 0.107]}
        >
          <mesh
            geometry={nodes.Cylinder007_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder007_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder007_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[4.099, 0.654, 0.855]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.165, 0.165, 0.126]}
        >
          <mesh
            geometry={nodes.Cylinder006_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder006_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder006_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.175, 1.344, -0.313]}
          rotation={[2.076, -1.1, 2.443]}
          scale={0.131}
        >
          <mesh
            geometry={nodes.Cylinder005_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder005_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder005_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.364, 1.108, -0.919]}
          rotation={[2.127, -1.07, 2.488]}
          scale={0.153}
        >
          <mesh
            geometry={nodes.Cylinder004_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder004_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder004_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group position={[3.837, -0.544, -3.479]} scale={[0.116, 0.116, 1]}>
          <mesh
            geometry={nodes.Cylinder001_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder001_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder001_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group position={[3.863, 0, -3.604]} scale={0.58}>
          <mesh
            geometry={nodes.Cylinder_0?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder_1?.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder_2?.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          position={[3.924, -0.883, 0.92]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.819, 0.775, 0.819]}
        >
          <mesh
            geometry={nodes.Cube037_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube037_1?.geometry}
            material={materials["Material.000"]}
          />
        </group>
        <group
          position={[3.922, -0.883, 0.92]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.819, 0.775, 0.819]}
        >
          <mesh
            geometry={nodes.Cube035_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube035_1?.geometry}
            material={materials["Material.009"]}
          />
        </group>
        <group
          position={[4.01, -0.417, 1.356]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.991, 0.938, 0.991]}
        >
          <mesh
            geometry={nodes.Cube034_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube034_1?.geometry}
            material={materials["Material.009"]}
          />
        </group>
        <group
          position={[4.012, -0.417, 1.356]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.991, 0.938, 0.991]}
        >
          <mesh
            geometry={nodes.Cube032_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube032_1?.geometry}
            material={materials["Material.000"]}
          />
        </group>
        <group
          position={[4.098, 0.104, 1.602]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.115, 0.991, 0.991]}
        >
          <mesh
            geometry={nodes.Cube031_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube031_1?.geometry}
            material={materials["Material.009"]}
          />
        </group>
        <group
          position={[4.1, 0.104, 1.602]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.115, 0.991, 0.991]}
        >
          <mesh
            geometry={nodes.Cube029_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube029_1?.geometry}
            material={materials["Material.000"]}
          />
        </group>
        <group
          position={[4.049, 0.662, 1.488]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        >
          <mesh
            geometry={nodes.Cube028_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube028_1?.geometry}
            material={materials["Material.000"]}
          />
        </group>
        <group
          position={[4.047, 0.662, 1.488]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        >
          <mesh
            geometry={nodes.Cube026_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube026_1?.geometry}
            material={materials["Material.009"]}
          />
        </group>
        <group
          position={[3.756, 0.008, -3.942]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        >
          <mesh
            geometry={nodes.Cube019_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube019_1?.geometry}
            material={materials["Material.000"]}
          />
        </group>
        <group
          position={[3.809, 0, -4.035]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        >
          <mesh
            geometry={nodes.Cube014_0?.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cube014_1?.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cube014_2?.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <mesh
          geometry={nodes.Cylinder002_0?.geometry}
          material={materials["Material.011"]}
          position={[3.835, 0.556, -1.312]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.347, 0.347, 0.381]}
        />
        <mesh
          geometry={nodes.Cube036_0?.geometry}
          material={materials["Material.012"]}
          position={[3.923, -0.883, 0.92]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.819, 0.775, 0.819]}
        />
        <mesh
          geometry={nodes.Cube033_0?.geometry}
          material={materials["Material.012"]}
          position={[4.011, -0.417, 1.356]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.991, 0.938, 0.991]}
        />
        <mesh
          geometry={nodes.Cube030_0?.geometry}
          material={materials["Material.012"]}
          position={[4.1, 0.104, 1.602]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.115, 0.991, 0.991]}
        />
        <mesh
          geometry={nodes.Cube027_0?.geometry}
          material={materials["Material.012"]}
          position={[4.048, 0.662, 1.488]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        />
        <mesh
          geometry={nodes.Cube025_0?.geometry}
          material={materials["Material.010"]}
          position={[3.94, -0.036, -1.895]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.376, 0.376, 0.193]}
        />
        <mesh
          geometry={nodes.Cube018_0?.geometry}
          material={materials["Material.012"]}
          position={[3.756, -0.017, -3.942]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        />
        <mesh
          geometry={nodes.Cube017_0?.geometry}
          material={materials["Material.012"]}
          position={[3.809, -0.014, -4.035]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.991}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/robotic_hand.glb");

// Exportar como padrão também para maior compatibilidade
export default Model;
